### ISSUE TITLE
Not building. media_service line 43

### ISSUE THREAD

**Issue by darrinps** [Roaa94/flutter-tutorials#1]
Seeing "The method 'byName' isn't defined for the type 'List'." on line 43 of media_service.

Looking at the documentation, it looks like that it isn't defined.

Also on that line, seeing "The getter 'name' isn't defined for the type 'AppImageSource'" for the appImageSource variable

That too seems like it is a valid error.

**Comment by Roaa94** [comment]
Please make sure you have dart version > 2.5

**Comment by Roaa94** [comment]
> Seeing "The method 'byName' isn't defined for the type 'List'." on line 43 of media_service.
> 
> Looking at the documentation, it looks like that it isn't defined.
> 
> Also on that line, seeing "The getter 'name' isn't defined for the type 'AppImageSource'" for the appImageSource variable
> 
> That too seems like it is a valid error.

Please make sure you have dart version > 2.15

**Comment by darrinps** [comment]
Upgrading dart did it. Closing this. Thanks!
